// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/jinzhu/gorm"
	"github.com/teten-nugraha/golang-crud-injection/product"
)

import (
	_ "github.com/jinzhu/gorm/dialects/mysql"
)

// Injectors from wire.go:

func InitProductAPI(db *gorm.DB) product.ProductAPI {
	productRepository := product.ProviderProductRepository(db)
	productService := product.ProviderProductService(productRepository)
	productAPI := product.ProvideProductAPI(productService)
	return productAPI
}
